apiVersion: v1
kind: Service
metadata:
  name: eticket-fe-cluster-ip-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: eticket-fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
