apiVersion: v1
kind: Service
metadata:
  name: frontend-cluster-ip-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
